pass = double(imread('passarinho.png'));
mont = double(imread('montanhas.jpeg'));
figure, imshow(uint8(pass)), title('Pássaro Orginal');
figure, imshow(uint8(mont)), title('Montanhas Orginal');
pass_fl2 = Floyd_Steinberg(pass,2);
pass_fl3 = Floyd_Steinberg(pass,3);
mont_fl2 = Floyd_Steinberg(mont,2);
mont_fl3 = Floyd_Steinberg(mont,3);
pass_od2 = ordered_dithering(pass,2);
pass_od3 = ordered_dithering(pass,3);
mont_od2 = ordered_dithering(mont,2);
mont_od3 = ordered_dithering(mont,3);
figure, imshow(pass_fl2,[]),title('Floyd-Steinberg 2 bits/pixel');
figure, imshow(pass_fl3,[]),title('Floyd-Steinberg 3 bits/pixel');
figure, imshow(mont_fl3,[]),title('Floyd-Steinberg 3 bits/pixel');
figure, imshow(mont_fl2,[]),title('Floyd-Steinberg 2 bits/pixel');
figure, imshow(pass_od2),title('Ordered Dithering 2 bits/pixel');
figure, imshow(pass_od3),title('Ordered Dithering 3 bits/pixel');
figure, imshow(mont_od3),title('Ordered Dithering 3 bits/pixel');
figure, imshow(mont_od2),title('Ordered Dithering 2 bits/pixel');